<a href="<?php echo $this->productInfoLink; ?>" class="">
    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
        <div class="thumbnail">
            <img class="pull-left media-object img-rounded" width="100%"
            src="<?php echo $this->baseUrl() . $this->product->image; ?>">
            <div class="caption">
                <h4><?php echo $this->product->name; ?></h4>
                <h5 class="list-price">
                    <?php echo money_format('%n', $this->product->price); ?>
                </h5>
            </div>
        </div>
    </div>
</a>
